# Generated by Django 4.1.6 on 2023-02-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Triange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side_one", models.IntegerField()),
                ("side_two", models.IntegerField()),
                ("side_three", models.IntegerField()),
                (
                    "triangle_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Equilateral", "Equilateral"),
                            ("Isosceles", "Isosceles"),
                            ("Scalene", "Scalene"),
                        ],
                        max_length=11,
                    ),
                ),
            ],
        ),
    ]
